services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bot:/bot
      - ./translations.json:/bot/translations.json
    restart: unless-stopped